[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ml_utils"
description = ""
version = "0.0.1"
dependencies = [
    "pyyaml",
    "pandas",
    "Jinja2",
    "aim",
    "accelerate",
    "numpy",
    "torch",
]
